apiVersion: v1
kind: Service

metadata:
  name: shadowdeploy-api

  labels:
    app: shadowdeploy-api

spec:
  selector:
    app: shadowdeploy-api

  ports:
    - name: http
      port: 8000
      targetPort: 8000

  type: ClusterIP