apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: shadowdeploy-api

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: shadowdeploy-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s